/**
 * The default wording of every template — E17/S2.
 *
 * In code, next to the variables each template understands and the sample data the preview uses.
 * The database holds only what the school has edited (`MailTemplate`); anything not edited renders
 * from here. The texts themselves are the ones `account-mail.ts` used to interpolate directly —
 * same sentences, with `{{placeholders}}` where the values went.
 *
 * Romanian bodies, per the standing exception: parents read these. Identifiers stay English.
 */

import { htmlFrame, linkBlock, paragraph, SIGNATURE } from './mail-frame';
import { TemplateFields } from './template-render';

export interface TemplateDefinition extends TemplateFields {
    key: string;
    /** What the admin screen calls it. */
    name: string;
    /** One sentence on when the message goes out. */
    description: string;
    /** The variables the template understands, with what each one holds. */
    variables: { name: string; description: string }[];
    /** What the preview renders with. Realistic, obviously fake. */
    sampleData: Record<string, string>;
}

export const TEMPLATE_DEFAULTS: readonly TemplateDefinition[] = [
    {
        key: 'email-confirmation',
        name: 'Confirmarea adresei de email',
        description: 'Pleacă la înregistrare, către adresa pe care a tastat-o părintele.',
        variables: [
            { name: 'firstName', description: 'Prenumele părintelui' },
            { name: 'confirmUrl', description: 'Linkul de confirmare, valabil 48 de ore' },
        ],
        sampleData: { firstName: 'Ana', confirmUrl: 'https://itbridgeschool.com/confirmare/exemplu' },
        subject: 'Confirmă adresa de email — IT Bridge School',
        bodyText: [
            'Bună, {{firstName}}!',
            '',
            'Ai creat un cont pe platforma IT Bridge School. Ca să confirmi că adresa aceasta este a ta,',
            'deschide linkul de mai jos:',
            '',
            '{{confirmUrl}}',
            '',
            'Linkul e valabil 48 de ore. După ce îl deschizi, contul mai are nevoie de o aprobare din',
            'partea noastră — te anunțăm printr-un email când e gata, de obicei în aceeași zi lucrătoare.',
            '',
            'Dacă nu tu ai cerut contul, ignoră mesajul: fără confirmare, contul nu poate fi folosit.',
            '',
            SIGNATURE,
        ].join('\n'),
        bodyHtml: htmlFrame(
            [
                paragraph('Bună, {{firstName}}!'),
                paragraph('Ai creat un cont pe platforma IT Bridge School. Ca să confirmi că adresa aceasta este a ta, deschide linkul de mai jos:'),
                linkBlock('confirmUrl'),
                paragraph(
                    'Linkul e valabil 48 de ore. După ce îl deschizi, contul mai are nevoie de o aprobare din partea noastră — te anunțăm printr-un email când e gata, de obicei în aceeași zi lucrătoare.',
                ),
                paragraph('Dacă nu tu ai cerut contul, ignoră mesajul: fără confirmare, contul nu poate fi folosit.'),
            ].join('\n'),
        ),
    },
    {
        key: 'legal-acceptance',
        name: 'Confirmarea acceptării termenilor',
        description: 'Pleacă la înregistrare și la fiecare versiune nouă acceptată din portal — confirmarea pe care o promit termenii la §4.7.',
        variables: [
            { name: 'firstName', description: 'Prenumele părintelui' },
            { name: 'acceptedOn', description: 'Ziua acceptării, în cuvinte' },
            { name: 'accepted', description: 'Ce s-a acceptat în ziua aceea, cu versiunile, ca o singură propoziție' },
            { name: 'termsVersion', description: 'Versiunea termenilor în vigoare' },
            { name: 'privacyVersion', description: 'Versiunea politicii de confidențialitate în vigoare' },
            { name: 'termsUrl', description: 'Pagina cu termenii și condițiile' },
            { name: 'privacyUrl', description: 'Pagina cu politica de confidențialitate' },
            { name: 'profileUrl', description: 'Pagina de profil din portal, unde rămâne evidența' },
        ],
        sampleData: {
            firstName: 'Ana',
            acceptedOn: '24 septembrie 2026',
            accepted:
                'Termenii și condițiile, versiunea 0.1; separat, clauzele de la §14, §15 și §18 din termeni — suspendarea, limitarea răspunderii și modificarea termenilor; Politica de confidențialitate, versiunea 0.1',
            termsVersion: '0.1',
            privacyVersion: '0.1',
            termsUrl: 'https://itbridgeschool.com/termeni',
            privacyUrl: 'https://itbridgeschool.com/confidentialitate',
            profileUrl: 'https://itbridgeschool.com/user/profile',
        },
        subject: 'Ai acceptat termenii IT Bridge School',
        bodyText: [
            'Bună, {{firstName}}!',
            '',
            'Îți confirmăm că pe {{acceptedOn}} ai acceptat, pentru contul tău de pe platforma IT Bridge School: {{accepted}}.',
            '',
            'Acordul tău cu școala e format acum din:',
            '- Termenii și condițiile, versiunea {{termsVersion}} — {{termsUrl}}',
            '- Politica de confidențialitate, versiunea {{privacyVersion}} — {{privacyUrl}}',
            '',
            'Versiunile acceptate, cu ziua fiecăreia, rămân pe contul tău și le găsești oricând la Profil: {{profileUrl}}',
            '',
            'Păstrează mesajul: e confirmarea acordului dintre tine și școală.',
            '',
            SIGNATURE,
        ].join('\n'),
        bodyHtml: htmlFrame(
            [
                paragraph('Bună, {{firstName}}!'),
                paragraph('Îți confirmăm că pe {{acceptedOn}} ai acceptat, pentru contul tău de pe platforma IT Bridge School: {{accepted}}.'),
                paragraph(
                    'Acordul tău cu școala e format acum din <a href="{{termsUrl}}">Termenii și condițiile</a>, versiunea {{termsVersion}}, și <a href="{{privacyUrl}}">Politica de confidențialitate</a>, versiunea {{privacyVersion}}.',
                ),
                paragraph('Versiunile acceptate, cu ziua fiecăreia, rămân pe contul tău și le găsești oricând la Profil:'),
                linkBlock('profileUrl'),
                paragraph('Păstrează mesajul: e confirmarea acordului dintre tine și școală.'),
            ].join('\n'),
        ),
    },
    {
        key: 'publication-consent-granted',
        name: 'Acordul pentru lucrările copilului',
        description:
            'Pleacă atunci când se consemnează acordul ca lucrările unui copil să apară în materialele școlii — din portal sau de birou (E07 S2). E confirmarea pe care o păstrează familia.',
        variables: [
            { name: 'firstName', description: 'Prenumele părintelui' },
            { name: 'childFirstName', description: 'Prenumele copilului' },
            { name: 'grantedOn', description: 'Ziua acordului, în cuvinte' },
            { name: 'recordedBy', description: 'Cine l-a consemnat: „din contul tău" sau „de birou, la cererea ta"' },
            { name: 'version', description: 'Versiunea textului acceptat' },
            { name: 'consentUrl', description: 'Pagina cu textul acordului' },
            { name: 'profileUrl', description: 'Pagina de profil din portal, de unde se retrage' },
        ],
        sampleData: {
            firstName: 'Ana',
            childFirstName: 'Matei',
            grantedOn: '25 septembrie 2026',
            recordedBy: 'din contul tău',
            version: '0.1',
            consentUrl: 'https://itbridgeschool.com/acord-lucrari',
            profileUrl: 'https://itbridgeschool.com/user/profile',
        },
        subject: 'Acordul pentru lucrările făcute de {{childFirstName}}',
        bodyText: [
            'Bună, {{firstName}}!',
            '',
            'Pe {{grantedOn}} s-a consemnat, {{recordedBy}}, acordul ca lucrările făcute de {{childFirstName}} la curs să poată apărea în materialele școlii: pe site, pe paginile școlii din rețelele sociale și în prezentări.',
            '',
            'Lângă o lucrare apar cel mult prenumele, inițiala numelui și vârsta. Nu fotografiem copiii — doar ecranul sau lucrarea.',
            '',
            'Textul acceptat, versiunea {{version}}:',
            '{{consentUrl}}',
            '',
            'Îl poți retrage oricând, dintr-o apăsare, la Profil:',
            '{{profileUrl}}',
            '',
            'Dacă nu tu l-ai dat, retrage-l de acolo și scrie-ne.',
            '',
            SIGNATURE,
        ].join('\n'),
        bodyHtml: htmlFrame(
            [
                paragraph('Bună, {{firstName}}!'),
                paragraph(
                    'Pe {{grantedOn}} s-a consemnat, {{recordedBy}}, acordul ca lucrările făcute de {{childFirstName}} la curs să poată apărea în materialele școlii: pe site, pe paginile școlii din rețelele sociale și în prezentări.',
                ),
                paragraph('Lângă o lucrare apar cel mult prenumele, inițiala numelui și vârsta. Nu fotografiem copiii — doar ecranul sau lucrarea.'),
                paragraph('<a href="{{consentUrl}}">Textul acceptat</a>, versiunea {{version}}. Îl poți retrage oricând, dintr-o apăsare, la Profil:'),
                linkBlock('profileUrl'),
                paragraph('Dacă nu tu l-ai dat, retrage-l de acolo și scrie-ne.'),
            ].join('\n'),
        ),
    },
    {
        key: 'publication-consent-revoked',
        name: 'Retragerea acordului pentru lucrările copilului',
        description:
            'Pleacă atunci când se consemnează retragerea acordului pentru lucrările unui copil — din portal sau de birou (E07 S2). Biroul primește în aceeași clipă mesajul lui intern.',
        variables: [
            { name: 'firstName', description: 'Prenumele părintelui' },
            { name: 'childFirstName', description: 'Prenumele copilului' },
            { name: 'revokedOn', description: 'Ziua retragerii, în cuvinte' },
            { name: 'recordedBy', description: 'Cine a consemnat-o: „din contul tău" sau „de birou, la cererea ta"' },
            { name: 'profileUrl', description: 'Pagina de profil din portal, de unde se poate da din nou' },
        ],
        sampleData: {
            firstName: 'Ana',
            childFirstName: 'Matei',
            revokedOn: '25 septembrie 2026',
            recordedBy: 'din contul tău',
            profileUrl: 'https://itbridgeschool.com/user/profile',
        },
        subject: 'Acordul pentru lucrările făcute de {{childFirstName}} a fost retras',
        bodyText: [
            'Bună, {{firstName}}!',
            '',
            'Pe {{revokedOn}} s-a consemnat, {{recordedBy}}, retragerea acordului pentru lucrările făcute de {{childFirstName}}.',
            '',
            'De acum nu le mai folosim în niciun material nou, iar ce publicasem deja pe site sau pe paginile noastre din rețelele sociale scoatem. Biroul a fost anunțat.',
            '',
            'Lucrările ajung la tine în continuare, ca până acum. Poți da acordul din nou oricând, la Profil:',
            '{{profileUrl}}',
            '',
            SIGNATURE,
        ].join('\n'),
        bodyHtml: htmlFrame(
            [
                paragraph('Bună, {{firstName}}!'),
                paragraph('Pe {{revokedOn}} s-a consemnat, {{recordedBy}}, retragerea acordului pentru lucrările făcute de {{childFirstName}}.'),
                paragraph(
                    'De acum nu le mai folosim în niciun material nou, iar ce publicasem deja pe site sau pe paginile noastre din rețelele sociale scoatem. Biroul a fost anunțat.',
                ),
                paragraph('Lucrările ajung la tine în continuare, ca până acum. Poți da acordul din nou oricând, la Profil:'),
                linkBlock('profileUrl'),
            ].join('\n'),
        ),
    },
    {
        key: 'publication-consent-revoked-office',
        name: 'Acord retras pentru lucrări (intern)',
        description:
            'Mesajul intern către birou când o familie retrage acordul pentru lucrările unui copil: ce era publicat trebuie scos de mână (E07 S2). Singurul destinatar e școala.',
        variables: [
            { name: 'childName', description: 'Numele complet al copilului' },
            { name: 'familyName', description: 'Numele complet al părintelui' },
            { name: 'grantedOn', description: 'Ziua din care era în vigoare acordul' },
            { name: 'revokedOn', description: 'Ziua retragerii' },
            { name: 'recordedBy', description: 'Cine a consemnat retragerea: „din portal, de familie" sau „de birou"' },
            { name: 'familyUrl', description: 'Pagina familiei, pe partea de admin' },
        ],
        sampleData: {
            childName: 'Matei Popescu',
            familyName: 'Ana Popescu',
            grantedOn: '1 septembrie 2026',
            revokedOn: '25 septembrie 2026',
            recordedBy: 'din portal, de familie',
            familyUrl: 'https://itbridgeschool.com/admin/profiles/12',
        },
        subject: 'Acord retras: lucrările făcute de {{childName}}',
        bodyText: [
            '{{familyName}} a retras acordul pentru lucrările făcute de {{childName}}, pe {{revokedOn}} ({{recordedBy}}). Acordul era în vigoare din {{grantedOn}}.',
            '',
            'De acum lucrările nu se mai folosesc în niciun material nou. Ce e deja publicat trebuie scos:',
            '- de pe site, dacă vreuna e în galeria unei pagini de curs;',
            '- de pe paginile școlii din rețelele sociale;',
            '- din prezentările și materialele încă netipărite.',
            '',
            'Platforma nu poate scoate nimic de acolo singură: site-ul public nu citește din ea, iar paginile din rețelele sociale sunt în afara ei.',
            '',
            'Familia:',
            '{{familyUrl}}',
            '',
            'Mesaj automat.',
        ].join('\n'),
        // Internal message — text is the whole point, nobody styles a to-do.
        bodyHtml: null,
    },
    {
        key: 'password-reset',
        name: 'Resetarea parolei',
        description: 'Pleacă doar când o familie cere linkul din formularul „am uitat parola". Valabil o oră.',
        variables: [
            { name: 'firstName', description: 'Prenumele părintelui' },
            { name: 'resetUrl', description: 'Linkul de resetare, valabil o oră' },
            { name: 'minutes', description: 'Câte minute e valabil linkul' },
        ],
        sampleData: { firstName: 'Ana', resetUrl: 'https://itbridgeschool.com/auth/reset-password?token=exemplu', minutes: '60' },
        subject: 'Resetarea parolei — IT Bridge School',
        bodyText: [
            'Bună, {{firstName}}!',
            '',
            'Cineva a cerut resetarea parolei pentru contul tău de pe platforma IT Bridge School.',
            'Dacă tu ai fost, deschide linkul de mai jos și alege o parolă nouă:',
            '',
            '{{resetUrl}}',
            '',
            'Linkul e valabil {{minutes}} de minute și poate fi folosit o singură dată. Dacă ceri altul,',
            'acesta nu mai merge.',
            '',
            'Dacă nu tu ai cerut, nu trebuie să faci nimic: parola rămâne cea veche, iar linkul expiră',
            'singur. Ne poți scrie oricând dacă ți se pare că altcineva încearcă să intre pe contul tău.',
            '',
            'După schimbarea parolei te vom deconecta de pe toate dispozitivele, ca nimeni altcineva să',
            'nu rămână conectat.',
            '',
            SIGNATURE,
        ].join('\n'),
        bodyHtml: htmlFrame(
            [
                paragraph('Bună, {{firstName}}!'),
                paragraph(
                    'Cineva a cerut resetarea parolei pentru contul tău de pe platforma IT Bridge School. Dacă tu ai fost, deschide linkul de mai jos și alege o parolă nouă:',
                ),
                linkBlock('resetUrl'),
                paragraph('Linkul e valabil {{minutes}} de minute și poate fi folosit o singură dată. Dacă ceri altul, acesta nu mai merge.'),
                paragraph(
                    'Dacă nu tu ai cerut, nu trebuie să faci nimic: parola rămâne cea veche, iar linkul expiră singur. Ne poți scrie oricând dacă ți se pare că altcineva încearcă să intre pe contul tău.',
                ),
                paragraph('După schimbarea parolei te vom deconecta de pe toate dispozitivele, ca nimeni altcineva să nu rămână conectat.'),
            ].join('\n'),
        ),
    },
    {
        key: 'account-approved',
        name: 'Contul a fost aprobat',
        description: 'Pleacă în clipa în care un admin aprobă familia, ca așteptarea să se termine cu un mesaj, nu cu o bănuială.',
        variables: [
            { name: 'firstName', description: 'Prenumele părintelui' },
            { name: 'portalUrl', description: 'Adresa de autentificare' },
        ],
        sampleData: { firstName: 'Ana', portalUrl: 'https://itbridgeschool.com/login' },
        subject: 'Contul tău IT Bridge School e activ',
        bodyText: [
            'Bună, {{firstName}}!',
            '',
            'Contul tău a fost aprobat. Te poți autentifica aici:',
            '',
            '{{portalUrl}}',
            '',
            'Următorul pas îl facem noi: îți repartizăm copilul într-o grupă potrivită ca vârstă și',
            'nivel. Dacă nu ne-am auzit încă despre asta, scrie-ne sau sună-ne și stabilim împreună.',
            '',
            SIGNATURE,
        ].join('\n'),
        bodyHtml: htmlFrame(
            [
                paragraph('Bună, {{firstName}}!'),
                paragraph('Contul tău a fost aprobat. Te poți autentifica aici:'),
                linkBlock('portalUrl'),
                paragraph(
                    'Următorul pas îl facem noi: îți repartizăm copilul într-o grupă potrivită ca vârstă și nivel. Dacă nu ne-am auzit încă despre asta, scrie-ne sau sună-ne și stabilim împreună.',
                ),
            ].join('\n'),
        ),
    },
    {
        key: 'account-rejected',
        name: 'Contul nu a fost activat',
        description: 'Pleacă atunci când un admin refuză un cont. Motivul refuzului rămâne în registru — e o notă între admini, nu o scrisoare.',
        variables: [
            { name: 'firstName', description: 'Prenumele părintelui' },
            { name: 'officeEmail', description: 'Adresa biroului, pentru contestații' },
        ],
        sampleData: { firstName: 'Ana', officeEmail: 'office@itbridgeschool.com' },
        subject: 'Despre contul tău IT Bridge School',
        bodyText: [
            'Bună, {{firstName}}!',
            '',
            'Îți mulțumim pentru interesul față de IT Bridge School. Deocamdată nu am putut activa contul',
            'creat cu această adresă.',
            '',
            'Dacă ți se pare o greșeală — și se poate întâmpla — scrie-ne la {{officeEmail}} și ne uităm încă o dată.',
            '',
            SIGNATURE,
        ].join('\n'),
        bodyHtml: htmlFrame(
            [
                paragraph('Bună, {{firstName}}!'),
                paragraph('Îți mulțumim pentru interesul față de IT Bridge School. Deocamdată nu am putut activa contul creat cu această adresă.'),
                paragraph('Dacă ți se pare o greșeală — și se poate întâmpla — scrie-ne la {{officeEmail}} și ne uităm încă o dată.'),
            ].join('\n'),
        ),
    },
    {
        key: 'absence-replacement',
        name: 'L-am mutat la altă grupă',
        description:
            'Pleacă în momentul în care biroul mută copilul, nu seara și nu automat. Spune un singur lucru, cel pe care familia nu-l știe: unde și când să-l aducă în locul orei pierdute.',
        variables: [
            { name: 'firstName', description: 'Prenumele părintelui' },
            { name: 'childName', description: 'Prenumele copilului mutat' },
            { name: 'missed', description: 'Ora pierdută — zi și oră, în cuvinte' },
            { name: 'replacement', description: 'Ora de înlocuire — grupă, zi, oră și sală' },
            { name: 'portalUrl', description: 'Linkul către absențele din cont' },
        ],
        sampleData: {
            firstName: 'Ana',
            childName: 'Maria',
            missed: 'miercuri, 9 septembrie, ora 16:00',
            replacement: 'grupa Python, joi, 10 septembrie, ora 18:00, sala Delta',
            portalUrl: 'https://itbridgeschool.com/user/absente',
        },
        subject: 'Ora de recuperare a lui {{childName}}',
        bodyText: [
            'Bună, {{firstName}}!',
            '',
            'Ne-ai anunțat din timp că {{childName}} nu ajunge la ora de {{missed}}, așa că am mutat-o pentru săptămâna asta la:',
            '',
            '{{replacement}}',
            '',
            'Nu trebuie să confirmi nimic — o așteptăm acolo. Detaliile sunt și în contul tău:',
            '',
            '{{portalUrl}}',
            '',
            'Dacă ora asta nu se potrivește, sună-ne și căutăm alta în aceeași săptămână.',
            '',
            SIGNATURE,
        ].join('\n'),
        bodyHtml: htmlFrame(
            [
                paragraph('Bună, {{firstName}}!'),
                paragraph('Ne-ai anunțat din timp că {{childName}} nu ajunge la ora de {{missed}}, așa că am mutat-o pentru săptămâna asta la:'),
                paragraph('{{replacement}}'),
                paragraph('Nu trebuie să confirmi nimic — o așteptăm acolo. Detaliile sunt și în contul tău:'),
                linkBlock('portalUrl'),
                paragraph('Dacă ora asta nu se potrivește, sună-ne și căutăm alta în aceeași săptămână.'),
            ].join('\n'),
        ),
    },
    {
        key: 'payment-due-soon',
        name: 'Factura se apropie de scadență',
        description: 'Pleacă cu trei zile înainte de termen, către o familie care nu a plătit încă. E o amintire, nu o somație.',
        variables: [
            { name: 'firstName', description: 'Prenumele părintelui' },
            { name: 'month', description: 'Luna facturată, în cuvinte' },
            { name: 'amount', description: 'Cât e de plată' },
            { name: 'dueOn', description: 'Ultima zi, în cuvinte' },
            { name: 'officeEmail', description: 'Adresa biroului' },
        ],
        sampleData: { firstName: 'Ana', month: 'martie', amount: '350 lei', dueOn: '15 martie', officeEmail: 'office@itbridgeschool.com' },
        subject: 'Factura pe {{month}}',
        bodyText: [
            'Bună, {{firstName}}!',
            '',
            'O amintire prietenoasă: factura pe {{month}}, {{amount}}, are termen până pe {{dueOn}}.',
            '',
            'Dacă ai plătit deja în ultimele zile, mesajul ăsta s-a încrucișat cu plata ta — ignoră-l.',
            'Dacă e ceva de lămurit, scrie-ne la {{officeEmail}} și rezolvăm.',
            '',
            SIGNATURE,
        ].join('\n'),
        bodyHtml: htmlFrame(
            [
                paragraph('Bună, {{firstName}}!'),
                paragraph('O amintire prietenoasă: factura pe {{month}}, <strong>{{amount}}</strong>, are termen până pe {{dueOn}}.'),
                paragraph('Dacă ai plătit deja în ultimele zile, mesajul ăsta s-a încrucișat cu plata ta — ignoră-l.'),
                paragraph('Dacă e ceva de lămurit, scrie-ne la {{officeEmail}} și rezolvăm.'),
            ].join('\n'),
        ),
    },
    {
        key: 'payment-overdue',
        name: 'Factura a depășit termenul',
        description: 'Pleacă după termen, la intervale. Tonul rămâne al unei școli care vorbește cu un părinte, nu al unui creditor.',
        variables: [
            { name: 'firstName', description: 'Prenumele părintelui' },
            { name: 'month', description: 'Luna facturată, în cuvinte' },
            { name: 'amount', description: 'Cât a rămas de plată' },
            { name: 'dueOn', description: 'Termenul care a trecut' },
            { name: 'officeEmail', description: 'Adresa biroului' },
        ],
        sampleData: { firstName: 'Ana', month: 'martie', amount: '350 lei', dueOn: '15 martie', officeEmail: 'office@itbridgeschool.com' },
        subject: 'Factura pe {{month}} a rămas neachitată',
        bodyText: [
            'Bună, {{firstName}}!',
            '',
            'Factura pe {{month}} avea termen pe {{dueOn}} și încă figurează neachitată la noi:',
            '{{amount}}.',
            '',
            'Se întâmplă, și de obicei e o scăpare, nu altceva. Dacă ai plătit și nu am înregistrat noi,',
            'spune-ne și verificăm — nu vrem să te căutăm degeaba.',
            '',
            'Dacă e o perioadă mai grea, scrie-ne la {{officeEmail}}. Preferăm să știm și să găsim o',
            'soluție împreună decât să nu mai vină copilul la ore.',
            '',
            SIGNATURE,
        ].join('\n'),
        bodyHtml: htmlFrame(
            [
                paragraph('Bună, {{firstName}}!'),
                paragraph('Factura pe {{month}} avea termen pe {{dueOn}} și încă figurează neachitată la noi: <strong>{{amount}}</strong>.'),
                paragraph(
                    'Se întâmplă, și de obicei e o scăpare, nu altceva. Dacă ai plătit și nu am înregistrat noi, spune-ne și verificăm — nu vrem să te căutăm degeaba.',
                ),
                paragraph(
                    'Dacă e o perioadă mai grea, scrie-ne la {{officeEmail}}. Preferăm să știm și să găsim o soluție împreună decât să nu mai vină copilul la ore.',
                ),
            ].join('\n'),
        ),
    },
    {
        key: 'payment-received',
        name: 'Am primit plata, factura e achitată',
        description: 'Pleacă în clipa în care o încasare acoperă factura. Confirmarea că banii au ajuns și că nu mai e nimic de plată.',
        variables: [
            { name: 'firstName', description: 'Prenumele părintelui' },
            { name: 'month', description: 'Luna facturată, în cuvinte' },
            { name: 'amount', description: 'Cât s-a încasat acum' },
            { name: 'paidOn', description: 'Ziua în care au intrat banii, în cuvinte' },
            { name: 'officeEmail', description: 'Adresa biroului' },
            { name: 'portalUrl', description: 'Pagina din portal cu facturile și plățile familiei' },
        ],
        sampleData: {
            firstName: 'Ana',
            month: 'martie',
            amount: '350 lei',
            paidOn: '5 martie',
            officeEmail: 'office@itbridgeschool.com',
            portalUrl: 'https://itbridgeschool.com/user/payments',
        },
        subject: 'Am primit plata pentru {{month}}',
        bodyText: [
            'Bună, {{firstName}}!',
            '',
            'Am înregistrat {{amount}} pe {{paidOn}}. Factura pe {{month}} e achitată integral —',
            'nu mai ai nimic de plată pe ea.',
            '',
            'Factura fiscală și, pentru numerar, chitanța le găsești în portal:',
            '{{portalUrl}}',
            '',
            'Dacă cifrele nu se potrivesc cu ce ai plătit tu, scrie-ne la {{officeEmail}} și verificăm.',
            '',
            SIGNATURE,
        ].join('\n'),
        bodyHtml: htmlFrame(
            [
                paragraph('Bună, {{firstName}}!'),
                paragraph(
                    'Am înregistrat <strong>{{amount}}</strong> pe {{paidOn}}. Factura pe {{month}} e achitată integral — nu mai ai nimic de plată pe ea.',
                ),
                paragraph('Factura fiscală și, pentru numerar, chitanța le găsești în portal:'),
                linkBlock('portalUrl'),
                paragraph('Dacă cifrele nu se potrivesc cu ce ai plătit tu, scrie-ne la {{officeEmail}} și verificăm.'),
            ].join('\n'),
        ),
    },
    {
        key: 'payment-received-partial',
        name: 'Am primit plata, mai rămâne o parte',
        description: 'Aceeași confirmare, când încasarea nu acoperă toată factura. Spune cât a rămas, ca familia să nu afle din următorul memento.',
        variables: [
            { name: 'firstName', description: 'Prenumele părintelui' },
            { name: 'month', description: 'Luna facturată, în cuvinte' },
            { name: 'amount', description: 'Cât s-a încasat acum' },
            { name: 'paidOn', description: 'Ziua în care au intrat banii, în cuvinte' },
            { name: 'outstanding', description: 'Cât a rămas de plată după această încasare' },
            { name: 'officeEmail', description: 'Adresa biroului' },
            { name: 'portalUrl', description: 'Pagina din portal cu facturile și plățile familiei' },
        ],
        sampleData: {
            firstName: 'Ana',
            month: 'martie',
            amount: '200 lei',
            paidOn: '5 martie',
            outstanding: '150 lei',
            officeEmail: 'office@itbridgeschool.com',
            portalUrl: 'https://itbridgeschool.com/user/payments',
        },
        subject: 'Am primit plata pentru {{month}}',
        bodyText: [
            'Bună, {{firstName}}!',
            '',
            'Am înregistrat {{amount}} pe {{paidOn}}, mulțumim. Pe factura din {{month}} mai rămân',
            '{{outstanding}}.',
            '',
            'Nu e nimic de făcut acum dacă așa ați stabilit. Dacă ai plătit mai mult și noi am',
            'înregistrat mai puțin, scrie-ne la {{officeEmail}} și verificăm.',
            '',
            'Factura fiscală și, pentru numerar, chitanța le găsești în portal:',
            '{{portalUrl}}',
            '',
            SIGNATURE,
        ].join('\n'),
        bodyHtml: htmlFrame(
            [
                paragraph('Bună, {{firstName}}!'),
                paragraph(
                    'Am înregistrat <strong>{{amount}}</strong> pe {{paidOn}}, mulțumim. Pe factura din {{month}} mai rămân <strong>{{outstanding}}</strong>.',
                ),
                paragraph(
                    'Nu e nimic de făcut acum dacă așa ați stabilit. Dacă ai plătit mai mult și noi am înregistrat mai puțin, scrie-ne la {{officeEmail}} și verificăm.',
                ),
                paragraph('Factura fiscală și, pentru numerar, chitanța le găsești în portal:'),
                linkBlock('portalUrl'),
            ].join('\n'),
        ),
    },
    {
        key: 'approval-needed',
        name: 'Cont nou în așteptare (intern)',
        description: 'Mesajul intern către birou: o familie s-a înregistrat și așteaptă aprobarea. Singurul destinatar e școala.',
        variables: [
            { name: 'parentName', description: 'Numele complet al părintelui' },
            { name: 'email', description: 'Adresa cu care s-a înregistrat' },
            { name: 'phone', description: 'Telefonul din profil, sau „încă necompletat" dacă familia nu a terminat pasul doi' },
            { name: 'approvalsUrl', description: 'Linkul către ecranul de aprobări' },
        ],
        sampleData: {
            parentName: 'Ana Popescu',
            email: 'ana.popescu@exemplu.ro',
            phone: '+40712345678',
            approvalsUrl: 'https://itbridgeschool.com/admin/approvals',
        },
        subject: 'Cont nou de părinte: {{parentName}}',
        bodyText: [
            '{{parentName}} și-a creat un cont și așteaptă aprobare.',
            '',
            'Email: {{email}}',
            'Telefon: {{phone}}',
            '',
            'Ecranul de aprobări:',
            '{{approvalsUrl}}',
            '',
            'Contul nu poate fi folosit până când nu e și confirmat prin email, și aprobat de un admin.',
            'Ecranul arată amândouă stările.',
            '',
            'Mesaj automat.',
        ].join('\n'),
        // Internal message — text is the whole point, nobody styles a nudge.
        bodyHtml: null,
    },
    {
        key: 'class-cancelled',
        name: 'Ora a fost anulată',
        description: 'Pleacă în clipa în care un admin anulează o ședință, către părinții copiilor din grupă și ai celor mutați acolo pentru săptămâna aceea.',
        variables: [
            { name: 'firstName', description: 'Prenumele părintelui' },
            { name: 'groupName', description: 'Numele grupei' },
            { name: 'date', description: 'Ziua orei anulate, în cuvinte' },
            { name: 'time', description: 'Ora la care ar fi început' },
            { name: 'reason', description: 'Motivul, așa cum l-a scris adminul' },
            {
                name: 'makeUpNote',
                description: 'Ce urmează: pentru grupă, că ora nu se facturează; pentru un copil mutat aici pe o săptămână, că școala îi caută altă oră',
            },
            { name: 'portalUrl', description: 'Adresa portalului; pentru un copil mutat aici, pagina cu absențele' },
        ],
        // What the group reads. The recovery credit this sample used to promise — "programează din
        // portal în următoarele 30 de zile" — was retired in E12/S4, and the editor's preview is the
        // one place an admin reads this message before a family does.
        sampleData: {
            firstName: 'Ana',
            groupName: 'Scratch începători',
            date: '12 martie',
            time: '16:00',
            reason: 'profesorul este bolnav',
            makeUpNote: 'Ora nu se facturează — plata e pe ședință ținută, deci luna aceasta va fi cu o ședință mai mică.',
            portalUrl: 'https://itbridgeschool.com/auth/login',
        },
        subject: 'Ora din {{date}} a fost anulată — {{groupName}}',
        bodyText: [
            'Bună, {{firstName}}!',
            '',
            'Ora de la grupa {{groupName}}, programată {{date}} la {{time}}, nu se mai ține. Motivul:',
            '{{reason}}.',
            '',
            '{{makeUpNote}}',
            '',
            'Restul orelor rămân neschimbate, iar orarul actualizat e mereu în portal:',
            '',
            '{{portalUrl}}',
            '',
            SIGNATURE,
        ].join('\n'),
        bodyHtml: htmlFrame(
            [
                paragraph('Bună, {{firstName}}!'),
                paragraph('Ora de la grupa <strong>{{groupName}}</strong>, programată {{date}} la {{time}}, nu se mai ține. Motivul: {{reason}}.'),
                paragraph('{{makeUpNote}}'),
                paragraph('Restul orelor rămân neschimbate, iar orarul actualizat e mereu în portal:'),
                linkBlock('portalUrl'),
            ].join('\n'),
        ),
    },
    {
        key: 'class-moved',
        name: 'Ora a fost mutată',
        description: 'Pleacă atunci când o ședință își schimbă ziua, ora sau sala, către părinții grupei.',
        variables: [
            { name: 'firstName', description: 'Prenumele părintelui' },
            { name: 'groupName', description: 'Numele grupei' },
            { name: 'fromWhen', description: 'Ziua, ora și sala de dinainte' },
            { name: 'toWhen', description: 'Ziua și ora nouă' },
            { name: 'room', description: 'Sala și locația unde se ține' },
            { name: 'reason', description: 'Motivul, așa cum l-a scris adminul' },
            { name: 'portalUrl', description: 'Adresa portalului' },
        ],
        sampleData: {
            firstName: 'Ana',
            groupName: 'Scratch începători',
            fromWhen: '12 martie, ora 16:00, Sala 1 — Sediul Titan',
            toWhen: '14 martie, ora 17:00',
            room: 'Sala 2 — Sediul Titan',
            reason: 'sala este ocupată de o evaluare',
            portalUrl: 'https://itbridgeschool.com/user/dashboard',
        },
        subject: 'Ora de la {{groupName}} se mută pe {{toWhen}}',
        bodyText: [
            'Bună, {{firstName}}!',
            '',
            'Ora de la grupa {{groupName}} se mută.',
            '',
            'Era: {{fromWhen}}',
            'Devine: {{toWhen}}',
            'Sala: {{room}}',
            '',
            'Motivul: {{reason}}.',
            '',
            'Orarul actualizat e în portal:',
            '',
            '{{portalUrl}}',
            '',
            SIGNATURE,
        ].join('\n'),
        bodyHtml: htmlFrame(
            [
                paragraph('Bună, {{firstName}}!'),
                paragraph('Ora de la grupa <strong>{{groupName}}</strong> se mută.'),
                paragraph('Era: {{fromWhen}}<br />Devine: <strong>{{toWhen}}</strong><br />Sala: {{room}}'),
                paragraph('Motivul: {{reason}}.'),
                paragraph('Orarul actualizat e în portal:'),
                linkBlock('portalUrl'),
            ].join('\n'),
        ),
    },
    {
        key: 'class-reinstated',
        name: 'Ora anulată se ține totuși',
        description: 'Pleacă atunci când o ședință anulată e reactivată — familia a fost anunțată că nu se ține, deci trebuie anunțată și că se ține.',
        variables: [
            { name: 'firstName', description: 'Prenumele părintelui' },
            { name: 'groupName', description: 'Numele grupei' },
            { name: 'date', description: 'Ziua orei, în cuvinte' },
            { name: 'time', description: 'Ora la care începe' },
            { name: 'portalUrl', description: 'Adresa portalului' },
        ],
        sampleData: {
            firstName: 'Ana',
            groupName: 'Scratch începători',
            date: '12 martie',
            time: '16:00',
            portalUrl: 'https://itbridgeschool.com/user/dashboard',
        },
        subject: 'Ora din {{date}} se ține totuși — {{groupName}}',
        bodyText: [
            'Bună, {{firstName}}!',
            '',
            'Revenim cu o veste bună: ora de la grupa {{groupName}} din {{date}}, ora {{time}}, se ține',
            'totuși. Te așteptăm cu cel mic, ca de obicei.',
            '',
            'Orarul e în portal:',
            '',
            '{{portalUrl}}',
            '',
            SIGNATURE,
        ].join('\n'),
        bodyHtml: htmlFrame(
            [
                paragraph('Bună, {{firstName}}!'),
                paragraph(
                    'Revenim cu o veste bună: ora de la grupa <strong>{{groupName}}</strong> din {{date}}, ora {{time}}, se ține totuși. Te așteptăm cu cel mic, ca de obicei.',
                ),
                paragraph('Orarul e în portal:'),
                linkBlock('portalUrl'),
            ].join('\n'),
        ),
    },
    {
        key: 'group-schedule-changed',
        name: 'Grupa își schimbă programul',
        description:
            'Pleacă o singură dată către fiecare familie a grupei, atunci când grupa se mută pe altă zi, altă oră sau în altă sală și orele ei viitoare se mută odată cu ea.',
        variables: [
            { name: 'firstName', description: 'Prenumele părintelui' },
            { name: 'groupName', description: 'Numele grupei' },
            { name: 'fromSlot', description: 'Ziua, ora și sala de până acum' },
            { name: 'toSlot', description: 'Ziua, ora și sala de acum încolo' },
            { name: 'firstDate', description: 'Prima oră ținută după programul nou, în cuvinte' },
            { name: 'portalUrl', description: 'Adresa portalului' },
        ],
        sampleData: {
            firstName: 'Ana',
            groupName: 'Scratch începători',
            fromSlot: 'luni, 16:00–17:30, Sala 1 — Sediul Titan',
            toSlot: 'miercuri, 17:00–18:30, Sala 2 — Sediul Titan',
            firstDate: '14 octombrie',
            portalUrl: 'https://itbridgeschool.com/user/dashboard',
        },
        subject: 'Grupa {{groupName}} își schimbă programul',
        bodyText: [
            'Bună, {{firstName}}!',
            '',
            'Grupa {{groupName}} își schimbă programul.',
            '',
            'Era: {{fromSlot}}',
            'Devine: {{toSlot}}',
            '',
            'Prima oră după programul nou e pe {{firstDate}}. Orarul actualizat e în portal:',
            '',
            '{{portalUrl}}',
            '',
            SIGNATURE,
        ].join('\n'),
        bodyHtml: htmlFrame(
            [
                paragraph('Bună, {{firstName}}!'),
                paragraph('Grupa <strong>{{groupName}}</strong> își schimbă programul.'),
                paragraph('Era: {{fromSlot}}<br>Devine: <strong>{{toSlot}}</strong>'),
                paragraph('Prima oră după programul nou e pe {{firstDate}}. Orarul actualizat e în portal:'),
                linkBlock('portalUrl'),
            ].join('\n'),
        ),
    },
];

export const TEMPLATE_KEYS = TEMPLATE_DEFAULTS.map((template) => template.key);

export function templateDefault(key: string): TemplateDefinition | undefined {
    return TEMPLATE_DEFAULTS.find((template) => template.key === key);
}
