import type { ColumnClassification, EntityInventory, PersonalColumn } from './data-inventory.types';

/**
 * Every column the platform stores, and what it is — E07 S1.
 *
 * The epic asks for one table naming each personal-data field, why it is held, on what legal basis,
 * for how long and who can see it. Its acceptance adds the part that makes this code rather than
 * prose: **a new column holding personal data cannot reach production without appearing here.**
 * `data-inventory.spec.ts` enforces exactly that — it reads TypeORM's own metadata and fails on any
 * column with no entry, and on any entry whose column is gone.
 *
 * So this file classifies *every* column, not only the personal ones. A field is either personal
 * data with the five answers filled in, or it is not, with a named reason from a short list. There
 * is no third state, because the third state is how a phone number ends up unclassified.
 *
 * **The privacy note is written from here, not beside it** (E22 S2). `docs/inventar-date.md` is
 * rendered from this file and checked for drift in the same spec, so the copy a family eventually
 * reads cannot be the one that fell behind.
 *
 * Two rules that decide most of the rows below, worth stating once:
 *
 * - **What makes a column personal is that it carries a fact about the person, not that it spells
 *   their name.** An invoice amount is not a number in the abstract; it is what *this* family owes,
 *   and marking money "not personal" because it holds no name is the mistake this file exists to
 *   prevent — GDPR's definition is information *relating to* an identifiable person, not
 *   information that identifies one. What stays outside is the row's own machinery: surrogate keys,
 *   write timestamps, internal plumbing. Those describe the row, not the person.
 * - **Deletion follows the row, not the column.** What goes when a family goes is decided per table
 *   by `linkedVia`, so a `createdAt` on a child's row is deleted with it whether or not it counts
 *   as personal data here. The two answer different questions: this file answers "what belongs in
 *   the privacy note", `linkedVia` answers "what disappears".
 * - **The school's own things are not personal data.** Rooms, timetables, holiday periods, mail
 *   templates, the branch address and phone: those are the school, not a data subject.
 */
export const DATA_INVENTORY: Record<string, EntityInventory> = {
    // ─────────────────────────────────────────────────────────── accounts and families

    User: {
        table: 'users',
        purpose: 'Contul de autentificare: cine se poate loga și cu ce rol.',
        subject: 'account-holder',
        linkedVia: 'profile',
        columns: {
            id: { personal: false, why: 'identifier' },
            username: {
                personal: true,
                about: 'account-holder',
                category: 'identity',
                purpose: 'Numele cu care se autentifică titularul contului.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            passwordHash: {
                personal: true,
                about: 'account-holder',
                category: 'credential',
                purpose: 'Verificarea parolei la autentificare.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['nobody'],
                note: 'Hash bcrypt, niciodată parola. Coloana e `select: false`: iese din bază doar cerută pe nume, de `AuthService.login`.',
            },
            role: {
                personal: true,
                about: 'account-holder',
                category: 'behavioural',
                purpose: 'Ce poate face contul în platformă.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            createdAt: { personal: false, why: 'row-timestamp' },
            emailConfirmedAt: {
                personal: true,
                about: 'account-holder',
                category: 'behavioural',
                purpose: 'Dovada că adresa de email chiar aparține familiei.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            approvalStatus: {
                personal: true,
                about: 'account-holder',
                category: 'behavioural',
                purpose: 'Dacă școala a recunoscut familia și i-a deschis contul.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            approvalDecidedAt: {
                personal: true,
                about: 'account-holder',
                category: 'behavioural',
                purpose: 'Când s-a luat decizia de aprobare.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            rejectionReason: {
                personal: true,
                about: 'account-holder',
                category: 'content',
                purpose: 'Motivul scris de admin la respingerea unui cont.',
                basis: 'legitimate_interest',
                retention: 'account',
                readableBy: ['admin'],
                note: 'Nota adminului. Nu se întoarce părintelui — de asta `parent.user` se scoate din răspunsuri.',
            },
        },
    },

    Profile: {
        table: 'profiles',
        purpose: 'Familia: cine e părintele și cum se ia legătura cu el.',
        subject: 'parent',
        linkedVia: 'self',
        columns: {
            id: { personal: false, why: 'identifier' },
            email: {
                personal: true,
                about: 'parent',
                category: 'contact',
                purpose: 'Facturi, chitanțe, anunțuri despre ore și proiectele copilului.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            phone: {
                personal: true,
                about: 'parent',
                category: 'contact',
                purpose: 'Contactul telefonic al școlii cu familia.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            firstName: {
                personal: true,
                about: 'parent',
                category: 'identity',
                purpose: 'Identificarea familiei pe ecrane, facturi și mesaje.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            lastName: {
                personal: true,
                about: 'parent',
                category: 'identity',
                purpose: 'Identificarea familiei pe ecrane, facturi și mesaje.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            address: {
                personal: true,
                about: 'parent',
                category: 'contact',
                purpose: 'Adresa de facturare.',
                basis: 'legal_obligation',
                retention: 'accounting',
                readableBy: ['admin', 'parent'],
            },
            emergencyContactName: {
                personal: true,
                about: 'parent',
                category: 'contact',
                purpose: 'Pe cine sună școala dacă i se întâmplă ceva copilului și părintele nu răspunde.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
                note: 'Poate fi o a treia persoană, care nu are cont: datele ei ajung aici prin părinte.',
            },
            emergencyContactRelation: {
                personal: true,
                about: 'parent',
                category: 'contact',
                purpose: 'Ce e persoana de urgență pentru copil.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            emergencyContactPhone: {
                personal: true,
                about: 'parent',
                category: 'contact',
                purpose: 'Numărul la care se sună în urgență.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            marketingOptIn: {
                personal: true,
                about: 'parent',
                category: 'behavioural',
                purpose: 'Dacă familia a acceptat comunicările comerciale.',
                basis: 'consent',
                retention: 'account',
                readableBy: ['admin', 'parent'],
                note: 'Implicit `false`. Gatează exclusiv `queueMarketing`; nicio factură și niciun anunț despre ore nu trece prin ea.',
            },
            unsubscribeToken: {
                personal: true,
                about: 'parent',
                category: 'credential',
                purpose: 'Recunoaște familia în linkul de dezabonare dintr-un mesaj promoțional (E17 S4).',
                basis: 'legal_obligation',
                retention: 'account',
                readableBy: ['admin'],
                note: 'Singura coloană de tip `credential` ținută în clar, și dinadins: linkul trimis prin e-mail trebuie să funcționeze peste luni, deci nu poate fi comparat cu un hash al unui secret pe care nu-l mai are nimeni. Ce face acceptabil compromisul e cât de puțin poate: oprește marketingul, niciodată nu-l pornește, și nu deschide nimic altceva. Nu apare în export și pe niciun ecran, iar ștergerea contului îl **rotește** (E07 S4) — altfel un link dintr-un mesaj de acum un an ar rămâne viu către rândul unei familii care a cerut să dispară.',
            },
            erasureRequestedAt: {
                personal: true,
                about: 'parent',
                category: 'behavioural',
                purpose: 'Ziua în care familia a cerut ștergerea contului; de la ea curge termenul de 30 de zile.',
                basis: 'legal_obligation',
                retention: 'account',
                readableBy: ['admin', 'parent'],
                note: 'O a doua cerere înainte ca prima să fie servită e aceeași cerere făcută de două ori: ziua dintâi rămâne.',
            },
            erasedAt: {
                personal: true,
                about: 'parent',
                category: 'behavioural',
                purpose: 'Ziua în care s-a făcut ștergerea.',
                basis: 'legal_obligation',
                retention: 'accounting',
                readableBy: ['admin'],
                note: 'Rândul supraviețuiește ștergerii fiindcă facturile atârnă de el (`Invoice.parent` e `CASCADE`). Coloana asta e ce spune ecranelor că e o coajă, nu o familie pe care n-a completat-o nimeni.',
            },
        },
    },

    Child: {
        table: 'children',
        purpose: 'Copilul înscris: cine e și în ce grupă intră.',
        subject: 'child',
        linkedVia: 'parent',
        columns: {
            id: { personal: false, why: 'identifier' },
            firstName: {
                personal: true,
                about: 'child',
                category: 'identity',
                purpose: 'Catalogul, orarul și fișa copilului.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            lastName: {
                personal: true,
                about: 'child',
                category: 'identity',
                purpose: 'Catalogul, orarul și fișa copilului.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            birthDate: {
                personal: true,
                about: 'child',
                category: 'identity',
                purpose: 'Potrivirea cu banda de vârstă a grupei.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
                note: 'Data nașterii unui minor. Verificarea de vârstă din E11 S6 e singurul lucru care o citește ca regulă.',
            },
            createdAt: { personal: false, why: 'row-timestamp' },
        },
    },

    // ─────────────────────────────────────────────────────────── participation

    Enrollment: {
        table: 'enrollments',
        purpose: 'Participarea unui copil la o grupă: de când, până când, în ce stare.',
        subject: 'child',
        linkedVia: 'child.parent',
        columns: {
            id: { personal: false, why: 'identifier' },
            status: {
                personal: true,
                about: 'child',
                category: 'participation',
                purpose: 'Dacă copilul e la probă, activ sau a ieșit.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            startDate: {
                personal: true,
                about: 'child',
                category: 'participation',
                purpose: 'De când vine copilul la grupă.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            endDate: {
                personal: true,
                about: 'child',
                category: 'participation',
                purpose: 'Când s-a încheiat participarea.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            exitReason: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'De ce a ieșit copilul din grupă.',
                basis: 'legitimate_interest',
                retention: 'account',
                readableBy: ['admin'],
                note: 'Text liber scris de birou despre o familie.',
            },
            contractSignedAt: {
                personal: true,
                about: 'child',
                category: 'participation',
                purpose: 'Ziua în care s-a semnat contractul pe hârtie (E07 S8).',
                basis: 'contract',
                retention: 'accounting',
                readableBy: ['admin', 'parent'],
                note: 'Doar faptul și ziua. Textul contractului nu e în platformă.',
            },
            createdAt: { personal: false, why: 'row-timestamp' },
        },
    },

    WaitlistEntry: {
        table: 'waitlist_entries',
        purpose: 'Cererea unui copil pentru o grupă plină, și oferta făcută când s-a eliberat un loc.',
        subject: 'child',
        linkedVia: 'child.parent',
        columns: {
            id: { personal: false, why: 'identifier' },
            status: {
                personal: true,
                about: 'child',
                category: 'participation',
                purpose: 'Unde stă cererea: în așteptare, ofertată, acceptată, expirată.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            createdAt: { personal: false, why: 'row-timestamp' },
            offeredAt: {
                personal: true,
                about: 'child',
                category: 'participation',
                purpose: 'Când i s-a oferit familiei locul eliberat.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            respondBy: {
                personal: true,
                about: 'child',
                category: 'participation',
                purpose: 'Până când ține oferta.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            note: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'Nota biroului pe cererea din listă.',
                basis: 'legitimate_interest',
                retention: 'account',
                readableBy: ['admin'],
            },
        },
    },

    Attendance: {
        table: 'attendances',
        purpose: 'Catalogul: dacă un copil a fost la o ședință.',
        subject: 'child',
        linkedVia: 'child.parent',
        columns: {
            id: { personal: false, why: 'identifier' },
            type: {
                personal: true,
                about: 'child',
                category: 'participation',
                purpose: 'În ce calitate a fost copilul la oră — înscris, la probă, la recuperare.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            present: {
                personal: true,
                about: 'child',
                category: 'participation',
                purpose: 'Prezența la ședință; stă la baza facturii lunii.',
                basis: 'contract',
                retention: 'accounting',
                readableBy: ['admin', 'parent'],
            },
        },
    },

    AbsenceNotice: {
        table: 'absence_notices',
        purpose: 'Anunțul familiei că un copil nu vine la o ședință.',
        subject: 'child',
        linkedVia: 'child.parent',
        columns: {
            id: { personal: false, why: 'identifier' },
            reason: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'Ce a spus familia — de obicei „răcit", „plecați din oraș".',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
                note: '**De semnalat avocatului.** Școala nu cere date de sănătate, dar câmpul e liber și părinții scriu „răcit", „varicelă" — deci poate primi date din art. 9 GDPR fără ca cineva să le fi cerut. Ce se face cu asta se decide în E22 S2; aici se consemnează doar că se poate întâmpla.',
            },
            inTime: {
                personal: true,
                about: 'child',
                category: 'participation',
                purpose: 'Dacă anunțul a venit înainte de termen — se îngheață la scriere.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            createdAt: { personal: false, why: 'row-timestamp' },
        },
    },

    SessionCountOverride: {
        table: 'session_count_overrides',
        purpose: 'Decizia biroului de a factura alt număr de ședințe decât cel numărat, pentru un copil, pe o lună.',
        subject: 'child',
        linkedVia: 'child.parent',
        columns: {
            id: { personal: false, why: 'identifier' },
            monthIssued: {
                personal: true,
                about: 'child',
                category: 'financial',
                purpose: 'Luna pe care se aplică decizia.',
                basis: 'contract',
                retention: 'accounting',
                readableBy: ['admin'],
            },
            sessions: {
                personal: true,
                about: 'child',
                category: 'financial',
                purpose: 'Numărul de ședințe facturat în locul celui numărat din catalog.',
                basis: 'contract',
                retention: 'accounting',
                readableBy: ['admin'],
            },
            reason: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'De ce s-a decis altfel decât spune catalogul.',
                basis: 'legitimate_interest',
                retention: 'accounting',
                readableBy: ['admin'],
            },
            createdAt: { personal: false, why: 'row-timestamp' },
            updatedAt: { personal: false, why: 'row-timestamp' },
        },
    },

    // ─────────────────────────────────────────────────────────── money

    Invoice: {
        table: 'invoices',
        purpose: 'Factura lunii pentru o familie.',
        subject: 'parent',
        linkedVia: 'parent',
        columns: {
            id: { personal: false, why: 'identifier' },
            amount: {
                personal: true,
                about: 'parent',
                category: 'financial',
                purpose: 'Cât datorează familia pe luna respectivă.',
                basis: 'legal_obligation',
                retention: 'accounting',
                readableBy: ['admin', 'parent'],
            },
            dateIssued: {
                personal: true,
                about: 'parent',
                category: 'financial',
                purpose: 'Data emiterii; de la ea curg cele 14 zile de termen.',
                basis: 'legal_obligation',
                retention: 'accounting',
                readableBy: ['admin', 'parent'],
            },
            monthIssued: {
                personal: true,
                about: 'parent',
                category: 'financial',
                purpose: 'Luna de curs facturată.',
                basis: 'legal_obligation',
                retention: 'accounting',
                readableBy: ['admin', 'parent'],
            },
            status: {
                personal: true,
                about: 'parent',
                category: 'financial',
                purpose: 'Dacă factura e neplătită, restantă, plătită sau anulată.',
                basis: 'legal_obligation',
                retention: 'accounting',
                readableBy: ['admin', 'parent'],
                note: 'O memorie, nu adevărul: restanța se derivă din plățile reușite (E16 S7).',
            },
        },
    },

    Payment: {
        table: 'payments',
        purpose: 'O sumă primită de la o familie pe o factură.',
        subject: 'parent',
        linkedVia: 'invoice.parent',
        columns: {
            id: { personal: false, why: 'identifier' },
            amount: {
                personal: true,
                about: 'parent',
                category: 'financial',
                purpose: 'Cât a plătit familia.',
                basis: 'legal_obligation',
                retention: 'accounting',
                readableBy: ['admin', 'parent'],
            },
            method: {
                personal: true,
                about: 'parent',
                category: 'financial',
                purpose: 'Cum a venit banul — numerar, transfer.',
                basis: 'legal_obligation',
                retention: 'accounting',
                readableBy: ['admin', 'parent'],
            },
            status: {
                personal: true,
                about: 'parent',
                category: 'financial',
                purpose: 'Dacă plata e inițiată, reușită, eșuată sau stornată.',
                basis: 'legal_obligation',
                retention: 'accounting',
                readableBy: ['admin', 'parent'],
            },
            date: {
                personal: true,
                about: 'parent',
                category: 'financial',
                purpose: 'Ziua plății.',
                basis: 'legal_obligation',
                retention: 'accounting',
                readableBy: ['admin', 'parent'],
            },
            externalReference: {
                personal: true,
                about: 'parent',
                category: 'financial',
                purpose: 'Referința din extrasul de cont, ca să se poată potrivi cu banca.',
                basis: 'legal_obligation',
                retention: 'accounting',
                readableBy: ['admin', 'parent'],
            },
            smartbillReference: {
                personal: true,
                about: 'parent',
                category: 'financial',
                purpose: 'Numărul documentului din SmartBill, când integrarea va exista.',
                basis: 'legal_obligation',
                retention: 'accounting',
                readableBy: ['admin'],
            },
            notes: {
                personal: true,
                about: 'parent',
                category: 'content',
                purpose: 'Nota biroului pe încasare.',
                basis: 'legitimate_interest',
                retention: 'accounting',
                readableBy: ['admin'],
            },
            createdAt: { personal: false, why: 'row-timestamp' },
        },
    },

    Discount: {
        table: 'discounts',
        purpose: 'O reducere acordată unei familii pe o lună.',
        subject: 'parent',
        linkedVia: 'parent',
        columns: {
            id: { personal: false, why: 'identifier' },
            name: {
                personal: true,
                about: 'parent',
                category: 'financial',
                purpose: 'Cum se numește reducerea pe factură — „Frate", „Recomandare".',
                basis: 'contract',
                retention: 'accounting',
                readableBy: ['admin', 'parent'],
            },
            description: {
                personal: true,
                about: 'parent',
                category: 'content',
                purpose: 'Explicația scrisă de birou lângă reducere.',
                basis: 'legitimate_interest',
                retention: 'accounting',
                readableBy: ['admin'],
            },
            type: {
                personal: true,
                about: 'parent',
                category: 'financial',
                purpose: 'Dacă reducerea e în lei sau în procente.',
                basis: 'contract',
                retention: 'accounting',
                readableBy: ['admin', 'parent'],
            },
            value: {
                personal: true,
                about: 'parent',
                category: 'financial',
                purpose: 'Cât se scade din factura familiei.',
                basis: 'contract',
                retention: 'accounting',
                readableBy: ['admin', 'parent'],
            },
            monthIssued: {
                personal: true,
                about: 'parent',
                category: 'financial',
                purpose: 'Luna pe care se aplică.',
                basis: 'contract',
                retention: 'accounting',
                readableBy: ['admin', 'parent'],
            },
        },
    },

    // ─────────────────────────────────────────────────────────── the child's work

    Project: {
        table: 'projects',
        purpose: 'O lucrare a unui copil, de la salvarea pe partajare până la trimiterea către familie.',
        subject: 'child',
        linkedVia: 'child.parent',
        columns: {
            id: { personal: false, why: 'identifier' },
            publicId: { personal: false, why: 'identifier', note: 'UUID pentru linkul de partajare; nu conține nimic despre copil.' },
            title: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'Numele lucrării, așa cum îl vede familia.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            description: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'Ce a scris profesorul despre lucrare.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            capturedOn: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'Când a fost salvată lucrarea.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            status: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'Dacă lucrarea e nouă, revizuită sau trimisă.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin'],
                note: 'Portalul arată doar `sent`: părintele nu vede ce n-a verificat încă nimeni.',
            },
            source: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'De unde a venit lucrarea — agent sau încărcare manuală.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin'],
            },
            hasThumbnail: { personal: false, why: 'state' },
            sentAt: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'Când a plecat lucrarea către familie.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            sentToEmail: {
                personal: true,
                about: 'parent',
                category: 'contact',
                purpose: 'Adresa la care s-a trimis efectiv, păstrată ca dovadă a trimiterii.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin'],
                note: 'O a doua copie a adresei părintelui, înghețată la momentul trimiterii. E07 S4 trebuie să o găsească și pe ea.',
            },
            sentOutboxMessageId: { personal: false, why: 'plumbing' },
            reassignedAt: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'Când s-a corectat atribuirea greșită a unei lucrări (E14 S7).',
                basis: 'legitimate_interest',
                retention: 'account',
                readableBy: ['admin'],
            },
            reassignedFromChildId: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'De la ce copil a fost mutată lucrarea.',
                basis: 'legitimate_interest',
                retention: 'account',
                readableBy: ['admin'],
                note: 'Trimite la un alt copil decât cel al rândului: e urma greșelii, și e chiar rostul coloanei.',
            },
            createdAt: { personal: false, why: 'row-timestamp' },
        },
    },

    ProjectVersion: {
        table: 'project_versions',
        purpose: 'O versiune a lucrării — copilul a salvat din nou.',
        subject: 'child',
        linkedVia: 'project.child.parent',
        columns: {
            id: { personal: false, why: 'identifier' },
            versionNumber: { personal: false, why: 'state' },
            createdAt: { personal: false, why: 'row-timestamp' },
        },
    },

    ProjectFile: {
        table: 'project_files',
        purpose: 'Un fișier al lucrării, urcat în bucket.',
        subject: 'child',
        linkedVia: 'version.project.child.parent',
        columns: {
            id: { personal: false, why: 'identifier' },
            originalName: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'Numele sub care a salvat copilul fișierul.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
                note: 'Copiii își pun numele în numele fișierului. De asta cheile de obiect se derivă din identificatori, nu din el.',
            },
            contentType: { personal: false, why: 'plumbing' },
            sizeBytes: { personal: false, why: 'plumbing' },
            ingestionKey: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'Cheia de idempotență la încărcare: copilul plus hash-ul conținutului.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['nobody'],
                note: '`{childId}:{sha256}` — conține id-ul copilului, deci e legată de el, chiar dacă nu se citește înapoi nicăieri.',
            },
            uploadedAt: { personal: false, why: 'row-timestamp' },
            createdAt: { personal: false, why: 'row-timestamp' },
        },
    },

    ProjectLink: {
        table: 'project_links',
        purpose: 'O legătură pusă lângă lucrare — Scratch, un site.',
        subject: 'child',
        linkedVia: 'project.child.parent',
        columns: {
            id: { personal: false, why: 'identifier' },
            label: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'Cum se numește legătura.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
            },
            url: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'Unde duce — de obicei proiectul copilului pe un site terț.',
                basis: 'contract',
                retention: 'account',
                readableBy: ['admin', 'parent'],
                note: 'Poate conține numele de utilizator al copilului pe acel site.',
            },
            createdAt: { personal: false, why: 'row-timestamp' },
        },
    },

    UnassignedFile: {
        table: 'unassigned_files',
        purpose: 'Un fișier pe care agentul nu l-a putut atribui unui copil (E14 S2).',
        subject: 'child',
        linkedVia: null,
        columns: {
            id: { personal: false, why: 'identifier' },
            relativePath: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'Unde stătea fișierul pe partajare, ca adminul să se ducă să se uite.',
                basis: 'legitimate_interest',
                retention: 'operational',
                readableBy: ['admin'],
                note: 'Calea trece prin folderele copiilor, deci **poate conține numele unui copil** — și nu se poate lega de un rând `Child`, fiindcă tocmai asta a eșuat. De aceea `linkedVia` e `null`: E07 S4 nu poate găsi rândul pornind de la familie.',
            },
            fileName: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'Numele fișierului rătăcit.',
                basis: 'legitimate_interest',
                retention: 'operational',
                readableBy: ['admin'],
            },
            sizeBytes: { personal: false, why: 'plumbing' },
            reason: { personal: false, why: 'state' },
            reportKey: { personal: false, why: 'plumbing', note: 'Grup plus cale, hash-uit pentru idempotență.' },
            reportedAt: { personal: false, why: 'row-timestamp' },
            resolvedAt: { personal: false, why: 'state' },
        },
    },

    // ─────────────────────────────────────────────────────────── the funnel

    Lead: {
        table: 'leads',
        purpose: 'Tot ce e între „cineva a întrebat" și „s-a înscris" (E20).',
        subject: 'parent',
        linkedVia: 'profile',
        columns: {
            id: { personal: false, why: 'identifier' },
            status: {
                personal: true,
                about: 'parent',
                category: 'participation',
                purpose: 'Unde a ajuns familia în pâlnie.',
                basis: 'legitimate_interest',
                retention: 'operational',
                readableBy: ['admin'],
            },
            source: {
                personal: true,
                about: 'parent',
                category: 'behavioural',
                purpose: 'De unde a venit familia — formular, telefon, recomandare.',
                basis: 'legitimate_interest',
                retention: 'operational',
                readableBy: ['admin'],
            },
            channel: {
                personal: true,
                about: 'parent',
                category: 'behavioural',
                purpose: 'Pe ce canal a ajuns la școală.',
                basis: 'legitimate_interest',
                retention: 'operational',
                readableBy: ['admin'],
            },
            parentName: {
                personal: true,
                about: 'parent',
                category: 'identity',
                purpose: 'Cine a întrebat.',
                basis: 'legitimate_interest',
                retention: 'operational',
                readableBy: ['admin'],
                note: 'Scris de un formular public, înainte să existe vreun cont.',
            },
            parentEmail: {
                personal: true,
                about: 'parent',
                category: 'contact',
                purpose: 'Cum răspunde școala.',
                basis: 'legitimate_interest',
                retention: 'operational',
                readableBy: ['admin'],
            },
            parentPhone: {
                personal: true,
                about: 'parent',
                category: 'contact',
                purpose: 'Cum sună școala înapoi.',
                basis: 'legitimate_interest',
                retention: 'operational',
                readableBy: ['admin'],
            },
            childFirstName: {
                personal: true,
                about: 'child',
                category: 'identity',
                purpose: 'Despre ce copil e vorba.',
                basis: 'legitimate_interest',
                retention: 'operational',
                readableBy: ['admin'],
            },
            childLastName: {
                personal: true,
                about: 'child',
                category: 'identity',
                purpose: 'Despre ce copil e vorba.',
                basis: 'legitimate_interest',
                retention: 'operational',
                readableBy: ['admin'],
            },
            childBirthDate: {
                personal: true,
                about: 'child',
                category: 'identity',
                purpose: 'Ca să se vadă ce grupă i s-ar potrivi.',
                basis: 'legitimate_interest',
                retention: 'operational',
                readableBy: ['admin'],
                note: 'Data nașterii unui minor, scrisă dintr-un formular public. Cel mai sensibil câmp pe care îl poate scrie cineva fără cont.',
            },
            experience: {
                personal: true,
                about: 'child',
                category: 'content',
                purpose: 'Ce a spus părintele despre experiența copilului.',
                basis: 'legitimate_interest',
                retention: 'operational',
                readableBy: ['admin'],
            },
            noSeats: { personal: false, why: 'state', note: 'Cererea pe care școala nu a putut-o servi. Despre grupă, nu despre familie.' },
            lostReason: {
                personal: true,
                about: 'parent',
                category: 'content',
                purpose: 'De ce nu s-a înscris familia.',
                basis: 'legitimate_interest',
                retention: 'operational',
                readableBy: ['admin'],
            },
            notes: {
                personal: true,
                about: 'parent',
                category: 'content',
                purpose: 'Notele biroului după telefon.',
                basis: 'legitimate_interest',
                retention: 'operational',
                readableBy: ['admin'],
            },
            nextActionAt: {
                personal: true,
                about: 'parent',
                category: 'behavioural',
                purpose: 'Când se recontactează familia.',
                basis: 'legitimate_interest',
                retention: 'operational',
                readableBy: ['admin'],
            },
            lastActivityAt: {
                personal: true,
                about: 'parent',
                category: 'behavioural',
                purpose: 'Când s-a mișcat ultima oară ceva pe lead.',
                basis: 'legitimate_interest',
                retention: 'operational',
                readableBy: ['admin'],
            },
            trialHeldAt: {
                personal: true,
                about: 'child',
                category: 'participation',
                purpose: 'Când a fost ținută lecția de probă.',
                basis: 'legitimate_interest',
                retention: 'operational',
                readableBy: ['admin'],
            },
            decidedAt: {
                personal: true,
                about: 'parent',
                category: 'behavioural',
                purpose: 'Când s-a hotărât familia, într-un sens sau altul.',
                basis: 'legitimate_interest',
                retention: 'operational',
                readableBy: ['admin'],
            },
            bookingKey: { personal: false, why: 'plumbing', note: 'Idempotență pentru formularul public.' },
            createdAt: { personal: false, why: 'row-timestamp' },
            updatedAt: { personal: false, why: 'row-timestamp' },
        },
    },

    // ─────────────────────────────────────────────────────────── messages

    OutboxMessage: {
        table: 'outbox',
        purpose: 'Coada de mesaje: tot ce pleacă din backend trece pe aici.',
        subject: 'parent',
        linkedVia: null,
        columns: {
            id: { personal: false, why: 'identifier' },
            to: {
                personal: true,
                about: 'parent',
                category: 'contact',
                purpose: 'Adresa la care pleacă mesajul.',
                basis: 'contract',
                retention: 'operational',
                readableBy: ['admin'],
                note: 'Rândul nu are relație către `Profile` — coada e partajată și scrie și către birou. E07 S4 trebuie să caute după adresă, nu după legătură; de asta `linkedVia` e `null`.',
            },
            subject: {
                personal: true,
                about: 'parent',
                category: 'content',
                purpose: 'Subiectul mesajului trimis familiei.',
                basis: 'contract',
                retention: 'operational',
                readableBy: ['admin'],
            },
            bodyText: {
                personal: true,
                about: 'parent',
                category: 'content',
                purpose: 'Textul trimis familiei — poate numi copilul, factura sau ora anulată.',
                basis: 'contract',
                retention: 'operational',
                readableBy: ['admin'],
            },
            bodyHtml: {
                personal: true,
                about: 'parent',
                category: 'content',
                purpose: 'Aceeași scrisoare, în HTML.',
                basis: 'contract',
                retention: 'operational',
                readableBy: ['admin'],
            },
            status: { personal: false, why: 'state' },
            undeliverableReason: { personal: false, why: 'state' },
            attempts: { personal: false, why: 'plumbing' },
            nextAttemptAt: { personal: false, why: 'plumbing' },
            lastError: { personal: false, why: 'plumbing', note: 'Mesajul furnizorului. Poate cita adresa respinsă — de asta e citit doar de admin.' },
            dedupeKey: { personal: false, why: 'plumbing', note: 'Conține identificatori (`receipt:412`), niciodată nume.' },
            attachments: { personal: false, why: 'plumbing', note: 'Chei de obiect, nu octeți: cheile sunt derivate din identificatori.' },
            createdAt: { personal: false, why: 'row-timestamp' },
            sentAt: {
                personal: true,
                about: 'parent',
                category: 'behavioural',
                purpose: 'Când a plecat mesajul — dovada că familia a fost anunțată.',
                basis: 'contract',
                retention: 'operational',
                readableBy: ['admin'],
            },
        },
    },

    Announcement: {
        table: 'announcements',
        purpose: 'Un mesaj trimis de școală unei grupe, unei locații sau tuturor (E17 S7).',
        subject: 'none',
        linkedVia: null,
        columns: {
            id: { personal: false, why: 'identifier' },
            audience: { personal: false, why: 'school-content' },
            kind: { personal: false, why: 'school-content' },
            subject: { personal: false, why: 'school-content', note: 'Scris de școală. O verificare refuză să numească un copil fără confirmare explicită.' },
            bodyText: { personal: false, why: 'school-content' },
            recipientCount: { personal: false, why: 'state' },
            declinedCount: { personal: false, why: 'state' },
            dedupeKey: { personal: false, why: 'plumbing' },
            createdAt: { personal: false, why: 'row-timestamp' },
        },
    },

    MailTemplate: {
        table: 'mail_templates',
        purpose: 'Șabloanele din care se compun mesajele.',
        subject: 'none',
        linkedVia: null,
        columns: {
            id: { personal: false, why: 'identifier' },
            key: { personal: false, why: 'school-content' },
            subject: { personal: false, why: 'school-content' },
            bodyText: { personal: false, why: 'school-content' },
            bodyHtml: { personal: false, why: 'school-content' },
            version: { personal: false, why: 'state' },
            updatedAt: { personal: false, why: 'row-timestamp' },
        },
    },

    // ─────────────────────────────────────────────────────────── sessions, consent, evidence

    Session: {
        table: 'sessions',
        purpose: 'Un refresh token emis, ca să poată fi revocat.',
        subject: 'account-holder',
        linkedVia: 'user.profile',
        columns: {
            id: { personal: false, why: 'identifier' },
            tokenHash: {
                personal: true,
                about: 'account-holder',
                category: 'credential',
                purpose: 'Recunoașterea tokenului la reîmprospătare.',
                basis: 'contract',
                retention: 'self-expiring',
                readableBy: ['nobody'],
                note: 'SHA-256, niciodată tokenul: un backup scurs nu trebuie să dea nimănui sesiuni valide.',
            },
            familyId: { personal: false, why: 'plumbing', note: 'Identifică lanțul de tokenuri al unui login, nu persoana.' },
            createdAt: { personal: false, why: 'row-timestamp' },
            expiresAt: { personal: false, why: 'state' },
            revokedAt: {
                personal: true,
                about: 'account-holder',
                category: 'behavioural',
                purpose: 'Când s-a încheiat sesiunea — logout sau semnal de furt.',
                basis: 'contract',
                retention: 'self-expiring',
                readableBy: ['admin'],
            },
            userAgent: {
                personal: true,
                about: 'account-holder',
                category: 'behavioural',
                purpose: 'De pe ce dispozitiv s-a intrat, ca sesiunile să se poată deosebi într-o listă.',
                basis: 'legitimate_interest',
                retention: 'self-expiring',
                readableBy: ['admin', 'parent'],
                note: 'Trunchiat dinadins: cât să deosebești două sesiuni, nu cât să faci o amprentă.',
            },
        },
    },

    EmailConfirmation: {
        table: 'email_confirmations',
        purpose: 'Tokenul trimis la înregistrare, ca să se confirme adresa.',
        subject: 'account-holder',
        linkedVia: 'user.profile',
        columns: {
            id: { personal: false, why: 'identifier' },
            tokenHash: {
                personal: true,
                about: 'account-holder',
                category: 'credential',
                purpose: 'Recunoașterea linkului de confirmare.',
                basis: 'contract',
                retention: 'self-expiring',
                readableBy: ['nobody'],
            },
            email: {
                personal: true,
                about: 'account-holder',
                category: 'contact',
                purpose: 'Adresa care se confirmă — înghețată la emitere, ca o schimbare ulterioară să nu valideze altceva.',
                basis: 'contract',
                retention: 'self-expiring',
                readableBy: ['nobody'],
            },
            createdAt: { personal: false, why: 'row-timestamp' },
            expiresAt: { personal: false, why: 'state' },
            consumedAt: {
                personal: true,
                about: 'account-holder',
                category: 'behavioural',
                purpose: 'Când s-a deschis linkul.',
                basis: 'contract',
                retention: 'self-expiring',
                readableBy: ['admin'],
            },
        },
    },

    DocumentAcceptance: {
        table: 'document_acceptances',
        purpose: 'Ce versiune a cărui document a acceptat cine, și când (E22 S4).',
        subject: 'account-holder',
        linkedVia: 'user.profile',
        columns: {
            id: { personal: false, why: 'identifier' },
            document: {
                personal: true,
                about: 'account-holder',
                category: 'behavioural',
                purpose: 'Care document a fost acceptat.',
                basis: 'legal_obligation',
                retention: 'audit',
                readableBy: ['admin', 'parent'],
            },
            version: {
                personal: true,
                about: 'account-holder',
                category: 'behavioural',
                purpose: 'Ce versiune de text a citit familia — singura întrebare care contează dacă cineva întreabă.',
                basis: 'legal_obligation',
                retention: 'audit',
                readableBy: ['admin', 'parent'],
            },
            acceptedAt: {
                personal: true,
                about: 'account-holder',
                category: 'behavioural',
                purpose: 'Când a acceptat.',
                basis: 'legal_obligation',
                retention: 'audit',
                readableBy: ['admin', 'parent'],
            },
        },
    },

    AuditLog: {
        table: 'audit_log',
        purpose: 'Cine a schimbat ce și când, pe drumurile banilor (E07 S3).',
        subject: 'account-holder',
        linkedVia: null,
        columns: {
            id: { personal: false, why: 'identifier' },
            occurredAt: { personal: false, why: 'row-timestamp' },
            actorUserId: {
                personal: true,
                about: 'account-holder',
                category: 'behavioural',
                purpose: 'Ce cont a făcut schimbarea.',
                basis: 'legal_obligation',
                retention: 'audit',
                readableBy: ['admin'],
            },
            actorUsername: {
                personal: true,
                about: 'account-holder',
                category: 'behavioural',
                purpose: 'Numele contului, copiat la scriere ca urma să rămână citibilă după ștergerea lui.',
                basis: 'legal_obligation',
                retention: 'audit',
                readableBy: ['admin'],
                note: 'Denormalizat dinadins: o urmă care arată către un rând ce poate fi șters pierde exact intrările care contează.',
            },
            action: { personal: false, why: 'state' },
            entityType: { personal: false, why: 'plumbing' },
            entityId: { personal: false, why: 'plumbing', note: 'Trimite la rândul schimbat — o factură, o plată. Datele familiei stau acolo, nu aici.' },
            changes: {
                personal: true,
                about: 'parent',
                category: 'financial',
                purpose: 'Ce s-a schimbat: suma, data, starea — doar câmpurile care s-au mișcat.',
                basis: 'legal_obligation',
                retention: 'audit',
                readableBy: ['admin'],
                note: 'Numai drumurile banilor sunt consemnate azi. Ce se ține despre o schimbare de `Profile` sau `Child` e decizia deschisă din E07 S3, exact fiindcă acolo *valoarea* e data personală.',
            },
            note: { personal: false, why: 'plumbing', note: 'Identificatori („copil 5, luna 2026-10"), niciodată nume.' },
        },
    },

    // ─────────────────────────────────────────────────────────── the school itself

    Location: {
        table: 'locations',
        purpose: 'O adresă a școlii.',
        subject: 'none',
        linkedVia: null,
        columns: {
            id: { personal: false, why: 'identifier' },
            name: { personal: false, why: 'config' },
            slug: { personal: false, why: 'config' },
            street: { personal: false, why: 'config' },
            city: { personal: false, why: 'config' },
            district: { personal: false, why: 'config' },
            postalCode: { personal: false, why: 'config' },
            latitude: { personal: false, why: 'config' },
            longitude: { personal: false, why: 'config' },
            phone: { personal: false, why: 'config', note: 'Telefonul filialei, nu al unei persoane.' },
            email: { personal: false, why: 'config', note: 'Adresa filialei, nu a unei persoane.' },
            openingHours: { personal: false, why: 'config' },
            isActive: { personal: false, why: 'config' },
        },
    },

    Room: {
        table: 'rooms',
        purpose: 'O sală dintr-o locație.',
        subject: 'none',
        linkedVia: null,
        columns: {
            id: { personal: false, why: 'identifier' },
            name: { personal: false, why: 'config' },
            capacity: { personal: false, why: 'schedule' },
            computers: { personal: false, why: 'schedule' },
            hasProjector: { personal: false, why: 'schedule' },
            hasWhiteboard: { personal: false, why: 'schedule' },
            isActive: { personal: false, why: 'config' },
        },
    },

    Group: {
        table: 'groups',
        purpose: 'O grupă: sala, ziua și ora la care se ține.',
        subject: 'none',
        linkedVia: null,
        columns: {
            id: { personal: false, why: 'identifier' },
            name: { personal: false, why: 'schedule' },
            weekday: { personal: false, why: 'schedule' },
            startTime: { personal: false, why: 'schedule' },
            endTime: { personal: false, why: 'schedule' },
            capacity: { personal: false, why: 'schedule' },
            minAge: { personal: false, why: 'schedule', note: 'Banda de vârstă a grupei, nu vârsta cuiva.' },
            maxAge: { personal: false, why: 'schedule' },
            isActive: { personal: false, why: 'config' },
        },
    },

    ClassSession: {
        table: 'class_sessions',
        purpose: 'O ședință din orar.',
        subject: 'none',
        linkedVia: null,
        columns: {
            id: { personal: false, why: 'identifier' },
            date: { personal: false, why: 'schedule' },
            startTime: { personal: false, why: 'schedule' },
            endTime: { personal: false, why: 'schedule' },
            status: { personal: false, why: 'state' },
            notes: { personal: false, why: 'school-content', note: 'De ce s-a anulat ora — „Vacanța de iarnă". Despre oră, nu despre cineva.' },
            isVacation: { personal: false, why: 'state' },
        },
    },

    NonTeachingPeriod: {
        table: 'non_teaching_periods',
        purpose: 'Un interval în care școala nu ține cursuri.',
        subject: 'none',
        linkedVia: null,
        columns: {
            id: { personal: false, why: 'identifier' },
            name: { personal: false, why: 'school-content' },
            startDate: { personal: false, why: 'schedule' },
            endDate: { personal: false, why: 'schedule' },
            createdAt: { personal: false, why: 'row-timestamp' },
        },
    },

    AgentStatus: {
        table: 'agent_status',
        purpose: 'Ultimul lucru pe care l-a spus despre sine agentul din birou.',
        subject: 'none',
        linkedVia: null,
        columns: {
            id: { personal: false, why: 'identifier' },
            agentName: { personal: false, why: 'config', note: 'Numele serviciului, nu al unui om.' },
            lastSeenAt: { personal: false, why: 'state' },
            version: { personal: false, why: 'config' },
            watchedRoot: { personal: false, why: 'config', note: 'Rădăcina partajării. Sub ea sunt folderele copiilor, dar calea în sine e configurație.' },
            pendingFiles: { personal: false, why: 'state' },
            lastError: { personal: false, why: 'plumbing' },
        },
    },
};

/** Every personal-data column, flattened — what the privacy note and E07 S4 actually walk. */
export function personalColumns(): { entity: string; column: string; classification: PersonalColumn }[] {
    const out: { entity: string; column: string; classification: PersonalColumn }[] = [];
    for (const [entity, inventory] of Object.entries(DATA_INVENTORY)) {
        for (const [column, classification] of Object.entries(inventory.columns)) {
            if (isPersonal(classification)) out.push({ entity, column, classification });
        }
    }
    return out;
}

export function isPersonal(classification: ColumnClassification): classification is PersonalColumn {
    return classification.personal;
}
